apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-rob
  description: A sample backstage component
  tags:
    - inner-source
    - asos-core
spec:
  type: website
  lifecycle: production
  owner: sample@rob-bell.net
